"""empty message

Revision ID: f9c360423d02
Revises: c84c5d7c16ce
Create Date: 2020-08-10 14:19:38.680087

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'f9c360423d02'
down_revision = 'c84c5d7c16ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pccgis', sa.Column('geom', geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('rivergis', sa.Column('geom', geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rivergis', 'geom')
    op.drop_column('pccgis', 'geom')
    # ### end Alembic commands ###
